---
title: "Homework 4"
author: "Rebecca, Emily, Edvard, Niels & Ferdinando"
date: "8 novembre 2019"
output: 
  html_document:
    theme: cerulean
    highlight: tango
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    collapsed: TRUE

---

```{r setup, include=FALSE, warning=FALSE}
library(tidyverse)
```

#Problem 0: modify find_pi from Homework #3

###Estimate_pi function
```{r Estimate_pi function, warning= FALSE}

  estimate_pi <- function(B = 5000, seed = 10) {
   
    #Conditions for which the function stops 
  if (is.na(B) || is.character(B) || length(B) !=1 || B %% 1 != 0){
  stop("Please insert a positive and integer value for B")
  }
    if (is.na(seed) || is.character(seed) || length(seed) !=1 || seed %% 1 != 0){
   stop("seed needs to be positive and integer")
  }
      
    # set a seed
      set.seed(seed)

      # simulate B points
      points <- tibble(
          x = runif(n = B, min = -1, max = 1),
          y = runif(n = B, min = -1, max = 1),
          inside = rep(NA, B)
      )

      points <- points %>% 
        mutate( inside = ifelse((points[,1])^2 + (points[,2])^2<=1,1,0))
    
      estimated_pi <-  4*sum(points$inside)/B

      # create a new list
      rval <- list(
          estimated_pi = estimated_pi,
          points = points
      )

      # assign pi class to rval
      class(rval) <- "pi"

      # return rval
      return(rval)

  }

```
### Plot the result of estimate_pi
```{r Plot function for PI, fig.height=6, fig.width=6}
  plot.pi <- function(x) {

    #extract the coordinates from the list
      points <- x[["points"]]
     
      #plot 
      points %>% 
    ggplot(aes(x = x,y = y)) +
    geom_point(color = ifelse(points$inside == 1,"steelblue1","firebrick")) +
    annotate("path",
             x=0+1*cos(seq(0,2*pi,length.out=100)),
             y=0+1*sin(seq(0,2*pi,length.out=100))) +
    geom_rect(aes(xmin = -1, xmax = 1, ymin = -1, ymax = 1), color = "black", fill = alpha("grey",0), linetype = 3) +
    labs(title = "Plot of estimated PI Area", x = "x", y = "y")

  }

```

